// Mock data for demonstration without PostgreSQL
export const mockData = {
  hospitalInfo: {
    id: '1',
    name: 'Kiran Hospital, Srikalahasti',
    address: 'A.P.S.R.T.C Bus stand, Srikalahasti, Andhra Pradesh 517644, India',
    phone: '9494746400',
    email: 'kiran@gmail.com',
    description: 'Leading multi-specialty hospital providing high-class healthcare',
    foundedYear: 2010,
    totalBeds: 20,
    totalDoctors: 4,
    totalStaff: 10,
    emergencySupport: true,
  },
  users: [
    {
      id: 'user-1',
      email: 'admin@hospitaldemo.in',
      password: '$2b$10$DXJ3SW6G7P50ecc3IZx5Pe..nzJ5zdq9O9zO9g9H9xH9xH9xH9xH9', // Admin@123 (hashed)
      firstName: 'Admin',
      lastName: 'User',
      role: 'SUPER_ADMIN',
      phone: '+91-9999999999',
      createdAt: new Date('2026-01-01'),
    },
    {
      id: 'user-2',
      email: 'doctor@hospitaldemo.in',
      password: '$2b$10$DXJ3SW6G7P50ecc3IZx5Pe..nzJ5zdq9O9zO9g9H9xH9xH9xH9xH9', // Doctor@123
      firstName: 'Dr. Rajesh',
      lastName: 'Kumar',
      role: 'DOCTOR',
      phone: '+91-9888888888',
      createdAt: new Date('2026-01-05'),
    },
    {
      id: 'user-3',
      email: 'patient@hospitaldemo.in',
      password: '$2b$10$DXJ3SW6G7P50ecc3IZx5Pe..nzJ5zdq9O9zO9g9H9xH9xH9xH9xH9', // Patient@123
      firstName: 'Arjun',
      lastName: 'Singh',
      role: 'PATIENT',
      phone: '+91-9777777777',
      createdAt: new Date('2026-01-10'),
    },
  ],
  departments: [
    {
      id: 'dept-1',
      name: 'Cardiology',
      slug: 'cardiology',
      description: 'Heart and cardiovascular care',
      doctorCount: 15,
      phone: '+91-11-4141-2100',
    },
    {
      id: 'dept-2',
      name: 'Orthopedics',
      slug: 'orthopedics',
      description: 'Bone and joint surgery',
      doctorCount: 12,
      phone: '+91-11-4141-2200',
    },
    {
      id: 'dept-3',
      name: 'Neurology',
      slug: 'neurology',
      description: 'Nervous system care',
      doctorCount: 10,
      phone: '+91-11-4141-2300',
    },
    {
      id: 'dept-4',
      name: 'Oncology',
      slug: 'oncology',
      description: 'Cancer treatment',
      doctorCount: 8,
      phone: '+91-11-4141-2400',
    },
    {
      id: 'dept-5',
      name: 'Pediatrics',
      slug: 'pediatrics',
      description: 'Child care and treatment',
      doctorCount: 18,
      phone: '+91-11-4141-2500',
    },
  ],
  doctors: [
    {
      id: 'doc-1',
      userId: 'user-2',
      departmentId: 'dept-1',
      specialization: 'Cardiology',
      qualifications: ['MBBS', 'MD Cardiology', 'DM Interventional Cardiology'],
      experience: 15,
      consultationFee: 50000, // in paisa = ₹500
      bio: 'Senior cardiologist with 15 years of experience in interventional cardiology',
      imageUrl: 'https://via.placeholder.com/300x400?text=Dr.Rajesh',
      available: true,
      createdAt: new Date('2026-01-05'),
    },
    {
      id: 'doc-2',
      departmentId: 'dept-2',
      specialization: 'Orthopedic Surgery',
      qualifications: ['MBBS', 'MS Orthopedics'],
      experience: 12,
      consultationFee: 40000, // ₹400
      bio: 'Specialist in joint replacement and arthroscopy',
      imageUrl: 'https://via.placeholder.com/300x400?text=Dr.Priya',
      available: true,
      createdAt: new Date('2026-01-06'),
    },
    {
      id: 'doc-3',
      departmentId: 'dept-3',
      specialization: 'Neurology',
      qualifications: ['MBBS', 'MD Neurology', 'DNB Neurology'],
      experience: 10,
      consultationFee: 45000, // ₹450
      bio: 'Expert in neurology and neurological disorders',
      imageUrl: 'https://via.placeholder.com/300x400?text=Dr.Amit',
      available: true,
      createdAt: new Date('2026-01-07'),
    },
  ],
  appointments: [
    {
      id: 'apt-1',
      patientId: 'user-3',
      doctorId: 'doc-1',
      departmentId: 'dept-1',
      appointmentDate: new Date('2026-03-15'),
      appointmentTime: '10:00 AM',
      reason: 'Regular checkup',
      status: 'APPROVED',
      notes: 'Follow-up for heart condition',
      createdAt: new Date('2026-03-01'),
    },
    {
      id: 'apt-2',
      patientId: 'user-3',
      doctorId: 'doc-2',
      departmentId: 'dept-2',
      appointmentDate: new Date('2026-03-18'),
      appointmentTime: '02:00 PM',
      reason: 'Knee pain consultation',
      status: 'PENDING',
      notes: 'Initial consultation for knee pain',
      createdAt: new Date('2026-03-05'),
    },
  ],
  blogPosts: [
    {
      id: 'blog-1',
      title: 'Understanding Heart Disease',
      slug: 'understanding-heart-disease',
      author: 'Dr. Rajesh Kumar',
      content: 'Heart disease is one of the leading causes of death. Learn about prevention and treatment...',
      status: 'PUBLISHED',
      publishedAt: new Date('2026-02-15'),
      views: 1250,
      createdAt: new Date('2026-02-15'),
    },
    {
      id: 'blog-2',
      title: 'Joint Health and Exercise',
      slug: 'joint-health-exercise',
      author: 'Dr. Priya Sharma',
      content: 'Maintaining joint health is crucial as we age. Here are some exercises to keep your joints healthy...',
      status: 'PUBLISHED',
      publishedAt: new Date('2026-02-20'),
      views: 950,
      createdAt: new Date('2026-02-20'),
    },
  ],
  healthPackages: [
    {
      id: 'pkg-1',
      name: 'Basic Health Checkup',
      price: 500000, // ₹5000
      description: 'Comprehensive basic health screening',
      tests: ['Blood Test', 'BP Check', 'BMI Assessment'],
      duration: '1 hour',
      createdAt: new Date('2026-01-01'),
    },
    {
      id: 'pkg-2',
      name: 'Advanced Cardiac Care',
      price: 1500000, // ₹15000
      description: 'Complete cardiac evaluation package',
      tests: ['ECG', 'Echocardiogram', 'Troponin Test', 'Cholesterol Panel'],
      duration: '3 hours',
      createdAt: new Date('2026-01-05'),
    },
    {
      id: 'pkg-3',
      name: 'Women Health Plus',
      price: 800000, // ₹8000
      description: 'Specialized women health screening',
      tests: ['Breast Examination', 'Pap Smear', 'Thyroid Profile', 'Gynecology Consultation'],
      duration: '2 hours',
      createdAt: new Date('2026-01-10'),
    },
  ],
  testimonials: [
    {
      id: 'test-1',
      patientName: 'Meera Gupta',
      patientEmail: 'meera@email.com',
      rating: 5,
      comment: 'Excellent service and very caring doctors. Highly recommended!',
      doctorId: 'doc-1',
      approved: true,
      createdAt: new Date('2026-02-01'),
    },
    {
      id: 'test-2',
      patientName: 'Ravi Patel',
      patientEmail: 'ravi@email.com',
      rating: 4,
      comment: 'Great medical expertise and modern facilities.',
      doctorId: 'doc-2',
      approved: true,
      createdAt: new Date('2026-02-05'),
    },
  ],
  insurancePartners: [
    {
      id: 'ins-1',
      name: 'ICICI Lombard',
      logoUrl: 'https://via.placeholder.com/200x100?text=ICICI',
      description: 'One of India\'s leading insurance companies',
    },
    {
      id: 'ins-2',
      name: 'Max Bupa',
      logoUrl: 'https://via.placeholder.com/200x100?text=MaxBupa',
      description: 'Health insurance and wellness partner',
    },
    {
      id: 'ins-3',
      name: 'Bajaj Allianz',
      logoUrl: 'https://via.placeholder.com/200x100?text=BajajAllianz',
      description: 'Trusted insurance provider',
    },
  ],
  careerOpenings: [
    {
      id: 'career-1',
      title: 'Senior Cardiologist',
      department: 'Cardiology',
      location: 'Delhi',
      description: 'Seeking experienced cardiologist for our cardiac center',
      experience: 10,
      qualification: 'MD/DM in Cardiology',
      createdAt: new Date('2026-02-01'),
    },
    {
      id: 'career-2',
      title: 'Registered Nurse',
      department: 'General',
      location: 'Bangalore',
      description: 'Multiple nursing positions available',
      experience: 2,
      qualification: 'B.Sc Nursing',
      createdAt: new Date('2026-02-10'),
    },
  ],
};
